[package]
name = "qualcul"
version = "0.1.0"
edition = "2024"

[dependencies]
cubecl = { version = "0.8.1", features = ["wgpu"] }
num = "0.4.3"
rand = "0.9.2"

[dev-dependencies]
criterion = "0.7.0"

[profile.dev]
opt-level = 2
debug = true

[[bench]]
name = "quantum_only"
harness = false
